In [1]:
import tensorflow as tf

tf.compat.v1.disable_eager_execution()  # ✅ MUST be called before defining variables



In [2]:
# To allow compatibility with TensorFlow 1.x code, we can use the `compat.v1` module.
# tf.compat.v1.disable_v2_behavior()


In [3]:
# Create a variable initialized to zero
zero = tf.Variable(0, name='zero')
one = tf.constant(1, name='one')


In [4]:
# create a new variable that adds zero and one
new_value = tf.add(zero, one, name='new_value')
# update the new value of zero
update = tf.compat.v1.assign(zero, new_value)

In [5]:
# assert new_value is not None, "new_value should not be None"
zero.assign(new_value)

<tf.Variable 'AssignVariableOp_1' shape=() dtype=int32>

In [6]:
# initialize variables
init_op = tf.compat.v1.global_variables_initializer()

In [7]:
sess = tf.compat.v1.Session()

In [8]:
# Creating a session to run the graph
sess.run(init_op)
print(sess.run(zero))  # Output: 0 (first run)



0


In [9]:
for _ in range(10):
    sess.run(update)
    print(sess.run(zero))  # Output should be 1 for each iteration  

1
2
3
4
5
6
7
8
9
10


<h2>String operations</h2>

In [10]:
hello = tf.constant(b"Hello", name='hello')  # Use b"Hello" for byte string
world = tf.constant(b"World", name='world')


In [11]:
hello_world = tf.add(hello, world, name='hello_world')


In [12]:

print(sess.run(hello_world))  # Output: b'HelloWorld'

b'HelloWorld'


<h2>Place holders</h2>

In [13]:
# Scalar placeholder
a_scalar = tf.compat.v1.placeholder(tf.float32, shape=(), name='a_scalar')
b_scalar = a_scalar * 2

In [14]:
result = sess.run(b_scalar, feed_dict={a_scalar: 3.0})
print("Scalar result:", result)  # Output: 6.0

Scalar result: 6.0


In [15]:

print("\n" + "-"*40 + "\n")


----------------------------------------



In [16]:
# Vector of Rank 1
a_vector = tf.compat.v1.placeholder(tf.float32, shape=[None], name='a_vector')
b_vector = a_vector * 2
result = sess.run(b_vector, feed_dict={a_vector: [3, 4, 5]})
print("1D vector result:", result)  # Output: [6.0, 8.0, 10.0]

1D vector result: [ 6.  8. 10.]


In [17]:
print("\n" + "-"*40 + "\n")


----------------------------------------



In [18]:
# Multidimensional Tensor (3D)
a_tensor = tf.compat.v1.placeholder(tf.float32, shape=[None, 7, 3], name='a_tensor')
b_tensor = a_tensor * 2
input_array = [[[1, 2, 4], [3, 4, 6], [5, 6, 9],
                [7, 8, 10], [11, 12, 14], [13, 14, 16], [15, 16, 18]]]
result = sess.run(b_tensor, feed_dict={a_tensor: input_array})
print("3D tensor result:\n", result)

3D tensor result:
 [[[ 2.  4.  8.]
  [ 6.  8. 12.]
  [10. 12. 18.]
  [14. 16. 20.]
  [22. 24. 28.]
  [26. 28. 32.]
  [30. 32. 36.]]]


In [19]:
# Close the earlier session when done
sess.close()

<h1>Re Creatina previous task with different approach</h1>

In [20]:
# Reopen a session to run the graph with the new operations
with tf.compat.v1.Session() as sess:
    print("Creating a variable 'zero' initialized to 0")
    zero = tf.Variable(0, name='zero')
    
    print("Creating a constant 'one' with value 1")
    one = tf.constant(1, name='one')
    
    print("Creating an operation to add zero and one")
    new_value = tf.add(zero, one, name='new_value')
    
    print("Creating an operation to assign new_value to zero")
    update = tf.compat.v1.assign(zero, new_value)
    
    print("Defining constants 'hello' and 'world'")
    hello = tf.constant(b"Hello", name='hello')
    world = tf.constant(b"World", name='world')
    
    print("Creating an operation to add 'hello' and 'world'")
    hello_world = tf.add(hello, world, name='hello_world')
    
    print("Creating a scalar placeholder 'a_scalar'")
    a_scalar = tf.compat.v1.placeholder(tf.float32, shape=(), name='a_scalar')
    b_scalar = a_scalar * 2

    print("Creating a 1D vector placeholder 'a_vector'")
    a_vector = tf.compat.v1.placeholder(tf.float32, shape=[None], name='a_vector')
    b_vector = a_vector * 2

    print("Creating a 3D tensor placeholder 'a_tensor'")
    a_tensor = tf.compat.v1.placeholder(tf.float32, shape=[None, 7, 3], name='a_tensor')
    b_tensor = a_tensor * 2

    print("Initializing all variables...")
    sess.run(tf.compat.v1.global_variables_initializer())

    print("\nRunning zero variable increment loop")
    print("Initial value of zero:", sess.run(zero))
    for i in range(10):
        sess.run(update)
        print(f"Value of zero after update {i + 1}:", sess.run(zero))

    print("\n" + "-"*40 + "\n")

    print("Running hello_world operation")
    result = sess.run(hello_world)
    print("Result of hello + world:", result)

    print("\n" + "-"*40 + "\n")

    print("Feeding scalar value 3.0 to placeholder 'a_scalar'")
    result = sess.run(b_scalar, feed_dict={a_scalar: 3.0})
    print("Result of a_scalar * 2:", result)

    print("\n" + "-"*40 + "\n")

    print("Feeding vector [3, 4, 5] to placeholder 'a_vector'")
    result = sess.run(b_vector, feed_dict={a_vector: [3, 4, 5]})
    print("Result of a_vector * 2:", result)

    print("\n" + "-"*40 + "\n")

    print("Feeding 3D tensor to placeholder 'a_tensor'")
    input_array = [[[1, 2, 4], [3, 4, 6], [5, 6, 9],
                    [7, 8, 10], [11, 12, 14], [13, 14, 16], [15, 16, 18]]]
    result = sess.run(b_tensor, feed_dict={a_tensor: input_array})
    print("Result of a_tensor * 2:\n", result)


Creating a variable 'zero' initialized to 0
Creating a constant 'one' with value 1
Creating an operation to add zero and one
Creating an operation to assign new_value to zero
Defining constants 'hello' and 'world'
Creating an operation to add 'hello' and 'world'
Creating a scalar placeholder 'a_scalar'
Creating a 1D vector placeholder 'a_vector'
Creating a 3D tensor placeholder 'a_tensor'
Initializing all variables...

Running zero variable increment loop
Initial value of zero: 0
Value of zero after update 1: 1
Value of zero after update 2: 2
Value of zero after update 3: 3
Value of zero after update 4: 4
Value of zero after update 5: 5
Value of zero after update 6: 6
Value of zero after update 7: 7
Value of zero after update 8: 8
Value of zero after update 9: 9
Value of zero after update 10: 10

----------------------------------------

Running hello_world operation
Result of hello + world: b'HelloWorld'

----------------------------------------

Feeding scalar value 3.0 to placeholde